language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "iojs"
before_script:
  - npm install -g mocha
  - npm install -g istanbul
script:
  - npm run-script test-travis
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js